# Generated by Django 4.1.7 on 2023-06-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="text",
            field=models.TextField(null=True),
        ),
    ]
