# Generated by Django 4.1.7 on 2023-06-14 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_message_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="room",
        ),
        migrations.RemoveField(
            model_name="message",
            name="text",
        ),
    ]
