# Generated by Django 4.1.7 on 2023-06-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0004_initial"),
        ("core", "0005_remove_message_room_message_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="room.room"
            ),
        ),
    ]
