# Generated by Django 4.1.7 on 2023-06-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="message",
        ),
        migrations.AddField(
            model_name="room",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
