# Generated by Django 4.1.7 on 2023-06-14 10:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0002_remove_room_message_room_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Room",
        ),
    ]
